# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c0c08d698020ca8cbc06ee91f4c3bcd98cbf5e2450640c2c3d9d8548e5a408d838010ba0ed667294ad6397814d877963b44eb31659b5e12035d1f187d91482a

test:
  secret_key_base: 57739fbe5c71a645308ffed7a7a427c9b6d4c3369cfc6e699a62d30780b3e11b7caeed3eb21ccff2d270311fbd8a8f50d38d614fa159abfa232830f75e092fc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
